all:
	fc-cache -f -v
link:
	ln -s texmf/tex/fonts/ ~/.fonts
linuxli-bertine:
	sudo apt-get install fonts-linuxlibertine
fonts-chines:
	sudo apt-get install ttf-wqy-microhei
copy:
	mkdir -p ~/.fonts
	cp * ~/.fonts


