mv _7letras.png 7letras.png
mv _aarea.png aarea.png
mv _bikini.jpeg bikini.jpeg
mv _bikini.png bikini.png
mv _camilawerner.png camilawerner.png
mv _cobogo.png cobogo.png
mv _educacaofinanceira.png educacaofinanceira.png
mv _logopoiese.png logopoiese.png
mv _patua.png patua.png
mv _saira.png saira.png
mv _ubu.png ubu.png